version: '3.8'

services:
  postgresdb:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgresql_custom
    container_name: postgresql_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - 8080:80
    depends_on:
      - postgresdb

volumes:
  db: