version: '3.8'

services:
  react:
    build:
      context: ./frontend
    image: node:alpine
    container_name: react
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"

  springboot:
    build:
      context: ./backend
    container_name: springboot
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8080:8080"


