version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgresql_custom
    container_name: postgresql_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database